export const destinations = [
    {
      id: 'yamunotri',
      name: 'Yamunotri',
      slug: 'yamunotri',
      tagline: 'Source of the Sacred Yamuna',
      deity: 'Goddess Yamuna',
      elevation: '3,293 m',
      bestTime: 'May - June & Sep - Nov',
      distance: '230 km from Rishikesh',
      description: 'Yamunotri is the source of the Yamuna river and the seat of the goddess Yamuna. It is the first of the four pilgrimages in the Char Dham yatra. Located in the Uttarkashi district, the temple sits amidst the majestic Himalayas.',
      longDescription: `Yamunotri, nestled in the western Garhwal Himalayas, is where the sacred Yamuna river originates. The pilgrimage begins here in the Char Dham circuit. The temple dedicated to Goddess Yamuna was built by Maharani Guleria of Jaipur in the 19th century. The actual source of the Yamuna is Champasar Glacier at Kalind Parvat (4,421 m), though the shrine is located at the hot springs of Yamunotri.
      
      Pilgrims traditionally cook rice and potatoes in the hot water of the kund (tank) and offer it to the goddess. The trek from Janki Chatti to the temple is approximately 6 km through scenic mountain terrain with beautiful rhododendron forests.`,
      highlights: ['Surya Kund Hot Springs', 'Divya Shila', 'Yamuna Mandir', 'Champasar Glacier', 'Saptarishi Kund'],
      trek: '6 km trek from Janki Chatti',
      image: '/Yamunotri.png',
      gallery: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
        'https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=600',
      ],
      openMonth: 'Akshaya Tritiya (April/May)',
      closeMonth: 'Diwali (October/November)',
      color: '#8B4513',
    },
    {
      id: 'gangotri',
      name: 'Gangotri',
      slug: 'gangotri',
      tagline: 'Where Goddess Ganga Descended',
      deity: 'Goddess Ganga',
      elevation: '3,048 m',
      bestTime: 'May - June & Sep - Oct',
      distance: '286 km from Rishikesh',
      description: 'Gangotri is the origin of the River Ganges and one of the holiest sites in Hinduism. The temple dedicated to Goddess Ganga stands at 3,048 meters amidst breathtaking Himalayan scenery.',
      longDescription: `Gangotri, located in the Uttarkashi district of Uttarakhand, is where the Bhagirathi River (as the Ganges is known here) originates from the Gangotri Glacier. According to Hindu mythology, it was here that King Bhagirath performed severe penance to bring the sacred river Ganga from heaven to earth to liberate the souls of his ancestors.
      
      The Gangotri temple was built by Amar Singh Thapa, a Nepali general, in the early 18th century. The area around Gangotri is a biodiversity hotspot and part of the Gangotri National Park. The actual source of the Ganges is at Gaumukh (Cow's Mouth), located 19 km from Gangotri, at an elevation of 4,023 meters.`,
      highlights: ['Gangotri Temple', 'Bhagirath Shila', 'Kedar Tal', 'Gaumukh Glacier', 'Nandanvan'],
      trek: 'Motor road accessible; Gaumukh 19 km trek',
      image: '/Gangotri.jpg',
      gallery: [
        'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600',
        'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600',
        'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600',
      ],
      openMonth: 'Akshaya Tritiya (April/May)',
      closeMonth: 'Diwali (October/November)',
      color: '#1B6FA8',
    },
    {
      id: 'kedarnath',
      name: 'Kedarnath',
      slug: 'kedarnath',
      tagline: 'The Abode of Lord Shiva',
      deity: 'Lord Shiva (Jyotirlinga)',
      elevation: '3,583 m',
      bestTime: 'May - June & Sep - Oct',
      distance: '223 km from Rishikesh',
      description: 'Kedarnath is one of the twelve Jyotirlingas of Lord Shiva. Situated in the Rudraprayag district, this ancient temple is surrounded by snow-capped peaks and the sacred Mandakini River.',
      longDescription: `Kedarnath is the most revered of the Char Dham pilgrimages. The Kedarnath temple is one of the 12 Jyotirlingas of Lord Shiva and is believed to have been built by the Pandavas and later renovated by Adi Shankaracharya in the 8th century. The temple stands at 3,583 meters, backed by the magnificent Kedarnath Peak.
      
      The 16 km trek from Gaurikund to Kedarnath passes through stunning alpine meadows and is one of the most spiritually charged journeys in India. Helicopter services are also available. The temple features a beautiful conical rock formation worshipped as the hump of Shiva's bull Nandi, and the nearby Bhairavnath Temple must also be visited.`,
      highlights: ['Kedarnath Jyotirlinga', 'Bhairavnath Temple', 'Vasuki Tal', 'Chorabari Lake', 'Gandhi Sarovar'],
      trek: '16 km trek from Gaurikund (or helicopter)',
      image: '/hero.jpg',
      gallery: [
        'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600',
        'https://images.unsplash.com/photo-1594176062595-e0e61ef52b59?w=600',
        'https://images.unsplash.com/photo-1609952542840-df54cfdeed2b?w=600',
      ],
      openMonth: 'Akshaya Tritiya (April/May)',
      closeMonth: 'Kartik Poornima (November)',
      color: '#6B3A8B',
    },
    {
      id: 'badrinath',
      name: 'Badrinath',
      slug: 'badrinath',
      tagline: 'Vishnu\'s Sacred Himalayan Abode',
      deity: 'Lord Vishnu (Badri Narayan)',
      elevation: '3,133 m',
      bestTime: 'May - June & Sep - Nov',
      distance: '298 km from Rishikesh',
      description: 'Badrinath is one of the most sacred temples in India dedicated to Lord Vishnu. Located along the Alaknanda river, it is the last of the Char Dham pilgrimages and holds immense religious significance.',
      longDescription: `Badrinath temple, dedicated to Lord Vishnu in his Badrinarayan form, is situated along the Alaknanda river in the Chamoli district of Uttarakhand. One of the 108 Divya Desams (Vishnu temples), it was established by Adi Shankaracharya in the 8th century, though the site's sanctity predates recorded history.
      
      The temple is flanked by Nar and Narayan mountain ranges and is accessible by road from Joshimath. The region offers spectacular views of the Neelkantha peak. Mana village, just 3 km from Badrinath, is the last Indian village before the Tibet border and home to the legendary Vyas Gufa (cave) where sage Veda Vyasa is said to have written the Mahabharata.`,
      highlights: ['Badrinath Temple', 'Tapt Kund', 'Brahma Kapal', 'Mana Village', 'Valley of Flowers'],
      trek: 'Motor road accessible; nearby treks available',
      image: '/badrinath.jpg',
      gallery: [
        'https://images.unsplash.com/photo-1625477710566-cb5d8a799d3c?w=600',
        'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600',
        'https://images.unsplash.com/photo-1597953601374-1ff2d5640c85?w=600',
      ],
      openMonth: 'Akshaya Tritiya (April/May)',
      closeMonth: 'Kartik Poornima (November)',
      color: '#D4AF37',
    },
  ];
  
  export const packages = [
    {
      id: 'char-dham-12days',
      name: 'Complete Char Dham Yatra',
      duration: '12 Days / 11 Nights',
      destinations: ['Yamunotri', 'Gangotri', 'Kedarnath', 'Badrinath'],
      price: 28999,
      originalPrice: 34999,
      groupSize: '2-15 People',
      category: 'popular',
      badge: 'Most Popular',
      image: '/ChardhamYatra.webp',
      description: 'The complete sacred journey covering all four dhams with comfortable accommodation and guided puja.',
      highlights: ['All 4 Dhams covered', 'Helicopter option available', 'Experienced priest-guide', 'AC transport'],
      inclusions: ['Accommodation (3-star)', 'All meals (veg)', 'AC vehicle', 'Puja samagri', 'Panda/guide service', 'First aid kit'],
      exclusions: ['Personal expenses', 'Porter/pony charges', 'Helicopter charges', 'Travel insurance'],
      itinerary: [
        { day: 1, title: 'Haridwar / Rishikesh Arrival', description: 'Arrive at Haridwar, hotel check-in. Evening Ganga Aarti at Har Ki Pauri. Overnight stay.' },
        { day: 2, title: 'Haridwar to Barkot', description: 'Drive to Barkot (220 km / 8 hrs) via Dehradun and Mussoorie. Evening at leisure. Overnight at Barkot.' },
        { day: 3, title: 'Barkot to Yamunotri', description: 'Drive to Janki Chatti. Trek 6 km to Yamunotri. Perform puja at Yamunotri temple. Return trek to Janki Chatti. Drive back to Barkot.' },
        { day: 4, title: 'Barkot to Uttarkashi', description: 'Drive to Uttarkashi (100 km / 4 hrs). Visit Vishwanath Temple. Overnight at Uttarkashi.' },
        { day: 5, title: 'Uttarkashi to Gangotri', description: 'Drive to Gangotri (100 km / 3 hrs). Perform puja at Gangotri Temple. Dip in holy Ganga. Return to Uttarkashi. Overnight stay.' },
        { day: 6, title: 'Uttarkashi to Guptkashi', description: 'Drive to Guptkashi via Tehri (220 km / 8 hrs). Visit Kashi Vishwanath Temple. Overnight at Guptkashi.' },
        { day: 7, title: 'Guptkashi to Kedarnath', description: 'Drive to Gaurikund (30 km). Trek 16 km to Kedarnath. Perform puja at Kedarnath Jyotirlinga. Evening aarti darshan.' },
        { day: 8, title: 'Kedarnath to Guptkashi', description: 'Morning darshan at Kedarnath. Trek down to Gaurikund. Drive back to Guptkashi. Overnight stay.' },
        { day: 9, title: 'Guptkashi to Badrinath', description: 'Drive to Badrinath (200 km / 7 hrs) via Joshimath. Evening aarti at Badrinath temple. Overnight at Badrinath.' },
        { day: 10, title: 'Badrinath Darshan & Mana', description: 'Morning abhishek puja at Badrinath. Visit Mana village, Vyas Gufa, Bhim Pul. Tapt Kund bath. Overnight at Badrinath.' },
        { day: 11, title: 'Badrinath to Rishikesh', description: 'Drive to Rishikesh (300 km / 9 hrs). Evening at leisure. Overnight at Rishikesh.' },
        { day: 12, title: 'Rishikesh Departure', description: 'Morning yoga / local sightseeing. Transfer to Haridwar railway station / airport for departure.' },
      ]
    },
    {
      id: 'do-dham-7days',
      name: 'Do Dham Yatra (Kedarnath & Badrinath)',
      duration: '7 Days / 6 Nights',
      destinations: ['Kedarnath', 'Badrinath'],
      price: 15999,
      originalPrice: 19999,
      groupSize: '2-20 People',
      category: 'budget',
      badge: 'Best Value',
      image: '/do-dham-yatra.jpg',
      description: 'Focused journey to the two most sacred Himalayan shrines — Kedarnath and Badrinath.',
      highlights: ['Kedarnath Jyotirlinga', 'Badrinath Vishnu', 'Valley of Flowers nearby', 'Budget friendly'],
      inclusions: ['Accommodation (standard)', 'Breakfast & dinner', 'Transport', 'Guide service'],
      exclusions: ['Lunch', 'Personal expenses', 'Helicopter charges', 'Pony/porter charges'],
      itinerary: [
        { day: 1, title: 'Haridwar Arrival', description: 'Arrive Haridwar, hotel check-in. Evening Ganga Aarti.' },
        { day: 2, title: 'Haridwar to Guptkashi', description: 'Drive to Guptkashi via Devprayag and Rudraprayag.' },
        { day: 3, title: 'Kedarnath Darshan', description: 'Early morning drive to Gaurikund. Trek to Kedarnath. Evening aarti darshan.' },
        { day: 4, title: 'Kedarnath to Badrinath', description: 'Morning puja. Trek down. Drive to Badrinath via Joshimath.' },
        { day: 5, title: 'Badrinath Darshan', description: 'Abhishek puja. Visit Mana village and Tapt Kund.' },
        { day: 6, title: 'Badrinath to Rishikesh', description: 'Return journey to Rishikesh.' },
        { day: 7, title: 'Departure', description: 'Transfer to Haridwar / Dehradun airport.' },
      ]
    },
    {
      id: 'kedarnath-helicopter',
      name: 'Kedarnath Helicopter Package',
      duration: '2 Days / 1 Night',
      destinations: ['Kedarnath'],
      price: 12999,
      originalPrice: 15999,
      groupSize: '2-6 People',
      category: 'luxury',
      badge: 'VIP Experience',
      image: '/Kedarnath-Yatra-by-Helicopter.jpg',
      description: 'Luxury helicopter yatra to Kedarnath for VIP darshan with priority puja and premium stay.',
      highlights: ['Helicopter both ways', 'VIP darshan', 'Priority puja', 'Premium accommodation'],
      inclusions: ['Helicopter (return)', 'VIP darshan', 'Puja arrangements', '3-star accommodation', 'All meals', 'Local guide'],
      exclusions: ['Personal expenses', 'Travel insurance', 'Puja samagri cost'],
      itinerary: [
        { day: 1, title: 'Helicopter to Kedarnath', description: 'Early morning helicopter from Phata/Sersi. VIP darshan and special puja. Explore Bhairavnath temple. Overnight at Kedarnath.' },
        { day: 2, title: 'Return Journey', description: 'Morning abhishek puja. Helicopter back. Transfer to Haridwar.' },
      ]
    },
  ];
  
  export const testimonials = [
    {
      name: 'Ramesh Sharma',
      city: 'Delhi',
      rating: 5,
      text: 'An absolutely divine experience! The team arranged everything perfectly — from comfortable accommodation to priest for special puja at Kedarnath. Truly a life-changing journey.',
      package: 'Complete Char Dham Yatra',
      date: 'May 2024',
    },
    {
      name: 'Priya & Suresh Patel',
      city: 'Ahmedabad',
      rating: 5,
      text: 'We were a group of 8 seniors and the team was exceptionally caring and patient. The pony arrangements at Kedarnath and wheelchair at Badrinath were very thoughtful.',
      package: 'Do Dham Yatra',
      date: 'September 2024',
    },
    {
      name: 'Kavitha Menon',
      city: 'Chennai',
      rating: 5,
      text: 'The helicopter package to Kedarnath was worth every rupee. VIP darshan, special abhishek puja — felt like God\'s own blessing. Will recommend to everyone!',
      package: 'Kedarnath Helicopter',
      date: 'June 2024',
    },
    {
      name: 'Harjinder Singh',
      city: 'Chandigarh',
      rating: 5,
      text: 'Third time doing Char Dham with this company. The service gets better every year. Their local knowledge and relationships with temple priests is unmatched.',
      package: 'Complete Char Dham Yatra',
      date: 'October 2024',
    },
  ];
  
  export const faqs = [
    {
      question: 'What is the best time to do Char Dham Yatra?',
      answer: 'The best time for Char Dham Yatra is May-June and September-October. The temples open in April/May (Akshaya Tritiya) and close in October/November (Diwali/Kartik Poornima). Avoid monsoon season (July-August) due to heavy rainfall and landslide risk.',
    },
    {
      question: 'What is the registration process for Char Dham Yatra?',
      answer: 'Registration for Char Dham Yatra is mandatory. Pilgrims must register on the official Uttarakhand Tourism portal or at registration centers in Haridwar and Rishikesh. Our team handles all registration formalities for you.',
    },
    {
      question: 'Is the Char Dham Yatra trek difficult?',
      answer: 'The difficulty varies. Gangotri and Badrinath are accessible by road. Yamunotri requires a 6 km trek from Janki Chatti. Kedarnath has a 16 km challenging trek from Gaurikund. Helicopter services are available for Kedarnath. Pony and palanquin services are also available.',
    },
    {
      question: 'What documents are required for Char Dham Yatra?',
      answer: 'You need a valid photo ID (Aadhaar card, passport, or voter ID), recent passport-size photographs, and the mandatory Yatra Parchi (registration slip). Medical fitness certificate is recommended for senior citizens.',
    },
    {
      question: 'What is included in the Char Dham Yatra packages?',
      answer: 'Our packages typically include accommodation, vegetarian meals, AC transport, guide service, puja samagri, and first aid support. Premium packages include helicopter service and VIP darshan. Exclusions include personal expenses, porter charges, and travel insurance.',
    },
    {
      question: 'Is there a weight/health restriction for Char Dham Yatra?',
      answer: 'There is no official weight restriction, but good health is essential. Persons with serious heart conditions, respiratory issues, or mobility limitations should consult a doctor. Helicopter services cap at 75 kg per person. We recommend carrying altitude sickness medication.',
    },
  ];
  
  export const blogPosts = [
    {
      id: 'best-time-char-dham',
      title: 'Best Time for Char Dham Yatra 2025: Complete Month-by-Month Guide',
      slug: 'best-time-for-char-dham-yatra',
      excerpt: 'Planning your Char Dham Yatra? Discover the ideal months to visit Yamunotri, Gangotri, Kedarnath, and Badrinath for the best weather, less crowds, and divine blessings.',
      category: 'Travel Tips',
      readTime: '8 min read',
      date: 'January 15, 2025',
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      tags: ['Best Time', 'Season', 'Weather', 'Travel Tips'],
    },
    {
      id: 'kedarnath-helicopter',
      title: 'Kedarnath Helicopter Booking 2025: Complete Guide, Prices & Tips',
      slug: 'kedarnath-helicopter-booking-guide',
      excerpt: 'Everything you need to know about booking a Kedarnath helicopter — operators, prices, booking process, and insider tips to ensure a smooth VIP pilgrimage experience.',
      category: 'Booking Guide',
      readTime: '6 min read',
      date: 'February 1, 2025',
      image: 'https://images.unsplash.com/photo-1609952542840-df54cfdeed2b?w=600',
      tags: ['Kedarnath', 'Helicopter', 'Booking', 'VIP'],
    },
    {
      id: 'char-dham-packing-list',
      title: 'Char Dham Yatra Packing List: What to Carry and What to Leave',
      slug: 'char-dham-yatra-packing-list',
      excerpt: 'The ultimate packing checklist for Char Dham Yatra. From warm clothes for high altitudes to medicines and religious items — be fully prepared for your divine journey.',
      category: 'Preparation',
      readTime: '5 min read',
      date: 'February 10, 2025',
      image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
      tags: ['Packing', 'Preparation', 'Checklist'],
    },
    {
      id: 'char-dham-cost',
      title: 'Char Dham Yatra Cost 2025: Budget Breakdown & Money-Saving Tips',
      slug: 'char-dham-yatra-cost-2025',
      excerpt: 'Plan your Char Dham budget with our detailed cost breakdown — transportation, accommodation, food, puja, helicopter, and hidden costs you should know about.',
      category: 'Budget',
      readTime: '7 min read',
      date: 'February 20, 2025',
      image: 'https://images.unsplash.com/photo-1625477710566-cb5d8a799d3c?w=600',
      tags: ['Budget', 'Cost', 'Planning'],
    },
  ];